### ISSUE TITLE
[ERROR] Disabling ResourceWorld v1.9.7

### ISSUE THREAD

**Issue by SofyanTauridOdeMadi** [NikV2/ResourceWorld#28]
[15:32:25 ERROR]: Error occurred while enabling ResourceWorld v1.9.7 (Is it up to date?)
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at me.nik.resourceworld.files.Config$Setting.getBoolean(Config.java:211) ~[[TUI]-ResourceWorld.jar:?]
        at me.nik.resourceworld.ResourceWorld.onEnable(ResourceWorld.java:210) ~[[TUI]-ResourceWorld.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1615]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:32:25 INFO]: [ResourceWorld] Disabling ResourceWorld v1.9.7

**Comment by NikV2** [comment]
You did something wrong on your config.yml.
Try to reset it.

**Comment by 72stom** [comment]
```
settings:
  check_for_updates: true
  main_spawn_world: Spawn
  teleport_to_spawn_on_quit: true
  reset_format: '%days% hari %hours% jam %minutes% menit %seconds% detik'
world:
  enabled: true
  world_name: ALAM
  generate_structures: true
  world_type: NORMAL
  environment: NORMAL
  custom_seed:
    enabled: false
    seed: -686298914
  world_border:
    enabled: true
    size: 1000
  allow_pvp: true
  always_day: false
  disable_suffocation_damage: true
  difficulty: HARD
  keep_inventory_on_death: true
  automated_resets:
    enabled: true
    interval: 168
    store_time_on_shutdown: true
  commands_after_reset:
    enabled: true
    commands:
      - title @p title {\"text\":\"The Resource World\",\"color\":\"green\"}
      - title @p subtitle {\"text\":\"Has been Reset!\",\"color\":\"green\"}
  disabled_commands:
    enabled: false
    commands:
      - /sethome
      - /claim
      - /setwarp
      - /tpahere
nether:
  enabled: true
  world_name: BUMI_nether
  generate_structures: true
  portals:
    override: true
    vanilla_portal_ratio: true
    portal_world: BUMI
    only_resource: true
  world_type: NORMAL
  environment: NETHER
  custom_seed:
    enabled: false
    seed: -686298914
  world_border:
    enabled: true
    size: 1000
  allow_pvp: true
  disable_suffocation_damage: true
  difficulty: HARD
  keep_inventory_on_death: true
  automated_resets:
    enabled: true
    interval: 168
    store_time_on_shutdown: true
  commands_after_reset:
    enabled: true
    commands:
      - title @p title {\"text\":\"The Resource Nether\",\"color\":\"green\"}
      - title @p subtitle {\"text\":\"Has been Reset!\",\"color\":\"green\"}
  disabled_commands:
    enabled: false
    commands:
      - /sethome
      - /claim
      - /setwarp
      - /tpahere
end:
  enabled: true
  world_name: BUMI_the_end
  generate_structures: true
  portals:
    override: true
    portal_world: BUMI
    only_resource: true
  world_type: NORMAL
  environment: THE_END
  custom_seed:
    enabled: false
    seed: -686298914
  world_border:
    enabled: true
    size: 1500
  allow_pvp: true
  disable_suffocation_damage: true
  difficulty: HARD
  keep_inventory_on_death: false
  automated_resets:
    enabled: true
    interval: 168
    store_time_on_shutdown: trues
  commands_after_reset:
    enabled: true
    commands:
      - title @p title {\"text\":\"The Resource End\",\"color\":\"green\"}
      - title @p subtitle {\"text\":\"Has been Reset!\",\"color\":\"green\"}
  disabled_commands:
    enabled: false
    commands:
      - /sethome
      - /claim
      - /setwarp
      - /tpahere
teleport_settings:
  price: 0
  cooldown: 30
  delay: 3
  world_max_teleport_range: 800
  nether_max_teleport_range: 800
  end_max_teleport_range: 800
  effects:
    enabled: true
    effect: ABSORPTION
    duration: 5
    amplifier: 2
  sounds:
    enabled: true
    sound: ENTITY_ENDERMAN_TELEPORT

```
